--- # Outline to Playbook Translation
- hosts: containers
  user: nik
  sudo: yes        
  gather_facts: no
  tasks:
  - name: date/time stamp for when playbook starts
    raw: /usr/bin/date > /home/nik/playbook_start.log
  - name: install apache web server
    yum: pkg=httpd state=latest
  - name: start the web service
    service: name=httpd state=restarted
  - name: verify that web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install telnet
    yum: pkg=telnet state=installed
  - name: install lynx
    yum: pkg=lynx state=latest
  - name: log all the packegas install on the system
    raw: yum list installed > /home/nik/installed.log
  - name: date/time stamp for when playbook ends
    raw: /usr/bin/date > /home/nik/playbook_end.log
